project:
  type: website
  output-dir: docs

website:
  title: "Carles-Blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/carlesoctav
      - icon: twitter
        href: https://twitter.com/carlesoctav
format:
  html:
    theme: litera
    css: styles.css



